### ISSUE TITLE
Controller port 2 in Atari2600 core does not work

### ISSUE THREAD

**Issue by VNVdaddy** [CollectorVision/Phoenix2600#7]
Tried 2nd controller port for first time to play Stargate, which needs a 2nd controller to work.  It didn't.  Then tried a two player game of Missile Command and the 2nd controller still did not work.  Tried a different controller.  Still did not work.  Tried the 2nd controller port in CV mode on DK and it worked fine.  Seems to only be an issue on the 2600 core.  I have the latest 2600 core update from 11/23/19.

**Comment by CollectorVision** [comment]
This has been fixed with latest core upgrade version 4 (03/14/20).
